/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;
import database.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author biswajit
 */
public class SearchWindow extends javax.swing.JFrame {

    /**
     * Creates new form StatsWindow
     */
    public SearchWindow() {
        initComponents();
        // TODO add the list of county names to the comboBoxCountry using
       ResultSet res = Queries.getCountries(null);
        try {
            while (res.next()) {
                comboBoxTeamBatting.addItem(res.getString("Name"));
                comboBoxTeamBowling.addItem(res.getString("Name"));
                comboBoxTeamFielding.addItem(res.getString("Name"));
                comboBoxTeamCountry.addItem(res.getString("Name"));
            }} catch (SQLException ex) {
            ex.printStackTrace();
        }
        
        // batting combo box disable
        battingMatchesMin.setEnabled(false);
        battingMatchesMax.setEnabled(false);
        battingRunsMin.setEnabled(false);
        battingRunsMax.setEnabled(false);
        battingHighestMin.setEnabled(false);
        battingHighestMax.setEnabled(false);
        battingHundredsMin.setEnabled(false);
        battingHundredsMax.setEnabled(false);
        battingFiftiesMin.setEnabled(false);
        battingFiftiesMax.setEnabled(false);
        battingStrikeRateMin.setEnabled(false);
        battingStrikeRateMax.setEnabled(false);
        
        // balling combo box disable
        bowlingMatchesMin.setEnabled(false);
        bowlingMatchesMax.setEnabled(false);
        bowlingWicketsMin.setEnabled(false);
        bowlingWicketsMax.setEnabled(false);
        bowlingEconomyMin.setEnabled(false);
        bowlingEconomyMax.setEnabled(false);
        bowling5WicketMin.setEnabled(false);
        bowling5WicketMax.setEnabled(false);
        bowlingAverageMin.setEnabled(false);
        bowlingAverageMax.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JTabbedPanel = new javax.swing.JTabbedPane();
        panelBatting = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        comboBoxTeamBatting = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        battingMatchesMin = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        battingMatchesMax = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        battingRunsMin = new javax.swing.JSpinner();
        battingRunsMax = new javax.swing.JSpinner();
        battingHighestMin = new javax.swing.JSpinner();
        battingHighestMax = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        battingHundredsMin = new javax.swing.JSpinner();
        battingHundredsMax = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        battingFiftiesMin = new javax.swing.JSpinner();
        battingFiftiesMax = new javax.swing.JSpinner();
        jLabel21 = new javax.swing.JLabel();
        battingStrikeRateMin = new javax.swing.JSpinner();
        jLabel59 = new javax.swing.JLabel();
        battingStrikeRateMax = new javax.swing.JSpinner();
        battingMatchesPlayed = new javax.swing.JRadioButton();
        battingRunsScored = new javax.swing.JRadioButton();
        battingHighestScore = new javax.swing.JRadioButton();
        battingHundreds = new javax.swing.JRadioButton();
        battingFifties = new javax.swing.JRadioButton();
        battingStrikeRates = new javax.swing.JRadioButton();
        panelBalling = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        comboBoxTeamBowling = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        bowlingMatchesMin = new javax.swing.JSpinner();
        bowlingMatchesMax = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();
        bowlingWicketsMin = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();
        bowlingWicketsMax = new javax.swing.JSpinner();
        bowlingEconomyMin = new javax.swing.JSpinner();
        bowlingEconomyMax = new javax.swing.JSpinner();
        jLabel23 = new javax.swing.JLabel();
        bowling5WicketMin = new javax.swing.JSpinner();
        bowling5WicketMax = new javax.swing.JSpinner();
        jLabel25 = new javax.swing.JLabel();
        bowlingAverageMin = new javax.swing.JSpinner();
        jLabel27 = new javax.swing.JLabel();
        bowlingAverageMax = new javax.swing.JSpinner();
        bowlingMatchesPlayed = new javax.swing.JRadioButton();
        bowlingWicketsTaken = new javax.swing.JRadioButton();
        bowlingEconomyRate = new javax.swing.JRadioButton();
        bowling5Wickets = new javax.swing.JRadioButton();
        bowlingAverage = new javax.swing.JRadioButton();
        panelFielding = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        comboBoxTeamFielding = new javax.swing.JComboBox();
        jLabel30 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel31 = new javax.swing.JLabel();
        jSpinner21 = new javax.swing.JSpinner();
        jLabel32 = new javax.swing.JLabel();
        jSpinner22 = new javax.swing.JSpinner();
        jLabel33 = new javax.swing.JLabel();
        jSpinner23 = new javax.swing.JSpinner();
        jLabel34 = new javax.swing.JLabel();
        jSpinner24 = new javax.swing.JSpinner();
        jLabel35 = new javax.swing.JLabel();
        jSpinner25 = new javax.swing.JSpinner();
        jLabel36 = new javax.swing.JLabel();
        jSpinner26 = new javax.swing.JSpinner();
        jButton3 = new javax.swing.JButton();
        panelUmpire = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel38 = new javax.swing.JLabel();
        jSpinner27 = new javax.swing.JSpinner();
        jSpinner28 = new javax.swing.JSpinner();
        jLabel40 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        panelCountry = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        comboBoxTeamCountry = new javax.swing.JComboBox();
        jLabel42 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox();
        jLabel43 = new javax.swing.JLabel();
        jSpinner29 = new javax.swing.JSpinner();
        jLabel44 = new javax.swing.JLabel();
        jSpinner30 = new javax.swing.JSpinner();
        jLabel45 = new javax.swing.JLabel();
        jSpinner31 = new javax.swing.JSpinner();
        jLabel46 = new javax.swing.JLabel();
        jSpinner32 = new javax.swing.JSpinner();
        jLabel47 = new javax.swing.JLabel();
        jSpinner33 = new javax.swing.JSpinner();
        jLabel48 = new javax.swing.JLabel();
        jSpinner34 = new javax.swing.JSpinner();
        jButton5 = new javax.swing.JButton();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jSpinner35 = new javax.swing.JSpinner();
        jLabel51 = new javax.swing.JLabel();
        jSpinner36 = new javax.swing.JSpinner();
        jLabel52 = new javax.swing.JLabel();
        jSpinner37 = new javax.swing.JSpinner();
        jLabel53 = new javax.swing.JLabel();
        jSpinner38 = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        comboBoxTeamCountry1 = new javax.swing.JComboBox();
        jLabel55 = new javax.swing.JLabel();
        comboBoxTeamCountry2 = new javax.swing.JComboBox();
        jLabel56 = new javax.swing.JLabel();
        comboBoxTeamCountry3 = new javax.swing.JComboBox();
        jLabel57 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox();
        jLabel60 = new javax.swing.JLabel();
        comboBoxTeamCountry4 = new javax.swing.JComboBox();
        jLabel61 = new javax.swing.JLabel();
        comboBoxTeamCountry5 = new javax.swing.JComboBox();
        jButton6 = new javax.swing.JButton();
        jLabel62 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Find Stats");

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Search");

        jLabel2.setText("Team");

        jLabel4.setText("Format");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "Test", "ODI", "T20" }));

        jLabel6.setText("to");

        jLabel8.setText("to");

        jLabel10.setText("to");

        jLabel12.setText("to");

        jButton1.setText("Submit Query");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/sachin.jpeg"))); // NOI18N
        jLabel13.setText("jLabel13");

        jLabel21.setText("to");

        jLabel59.setText("to");

        battingMatchesPlayed.setText("Matches Played");
        battingMatchesPlayed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                battingMatchesPlayedActionPerformed(evt);
            }
        });

        battingRunsScored.setText("Runs Scored");
        battingRunsScored.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                battingRunsScoredActionPerformed(evt);
            }
        });

        battingHighestScore.setText("Highest Score");
        battingHighestScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                battingHighestScoreActionPerformed(evt);
            }
        });

        battingHundreds.setText("Hundreds");
        battingHundreds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                battingHundredsActionPerformed(evt);
            }
        });

        battingFifties.setText("Fifties");
        battingFifties.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                battingFiftiesActionPerformed(evt);
            }
        });

        battingStrikeRates.setText("Strike Rate");
        battingStrikeRates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                battingStrikeRatesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBattingLayout = new javax.swing.GroupLayout(panelBatting);
        panelBatting.setLayout(panelBattingLayout);
        panelBattingLayout.setHorizontalGroup(
            panelBattingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBattingLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(panelBattingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelBattingLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(113, 113, 113))
                    .addGroup(panelBattingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addGroup(panelBattingLayout.createSequentialGroup()
                            .addGroup(panelBattingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panelBattingLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(109, 109, 109))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelBattingLayout.createSequentialGroup()
                                    .addGroup(panelBattingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(battingMatchesPlayed, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(battingRunsScored, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(battingHighestScore, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(battingHundreds, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(battingFifties, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(battingStrikeRates, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(panelBattingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelBattingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(comboBoxTeamBatting, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, 188, Short.MAX_VALUE))
                                .addGroup(panelBattingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelBattingLayout.createSequentialGroup()
                                        .addComponent(battingStrikeRateMin, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel59)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(battingStrikeRateMax, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelBattingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(panelBattingLayout.createSequentialGroup()
                                            .addComponent(battingFiftiesMin, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel21)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(battingFiftiesMax, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelBattingLayout.createSequentialGroup()
                                            .addGroup(panelBattingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(battingMatchesMin, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(battingRunsMin, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(battingHighestMin, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(battingHundredsMin, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(panelBattingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(panelBattingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(panelBattingLayout.createSequentialGroup()
                                                        .addGroup(panelBattingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel8)
                                                            .addComponent(jLabel6))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addGroup(panelBattingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(battingMatchesMax, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(battingRunsMax, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(panelBattingLayout.createSequentialGroup()
                                                        .addComponent(jLabel10)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(battingHighestMax, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(panelBattingLayout.createSequentialGroup()
                                                    .addComponent(jLabel12)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(battingHundredsMax, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        panelBattingLayout.setVerticalGroup(
            panelBattingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBattingLayout.createSequentialGroup()
                .addGroup(panelBattingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBattingLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(panelBattingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(comboBoxTeamBatting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelBattingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelBattingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(battingMatchesMin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(battingMatchesMax, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(battingMatchesPlayed))
                        .addGap(22, 22, 22)
                        .addGroup(panelBattingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(battingRunsMin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(battingRunsMax, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(battingRunsScored))
                        .addGroup(panelBattingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBattingLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(panelBattingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(battingHighestMin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(battingHighestScore)))
                            .addGroup(panelBattingLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(battingHighestMax, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(panelBattingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(battingHundredsMin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(battingHundredsMax, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(battingHundreds))
                        .addGap(17, 17, 17)
                        .addGroup(panelBattingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(battingFiftiesMin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(battingFiftiesMax, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(battingFifties))
                        .addGap(16, 16, 16)
                        .addGroup(panelBattingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(battingStrikeRateMax, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel59)
                            .addComponent(battingStrikeRateMin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(battingStrikeRates)))
                    .addGroup(panelBattingLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        JTabbedPanel.addTab("        Batting        ", panelBatting);

        jLabel3.setText("Team");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/mcgrath.jpg"))); // NOI18N

        jButton2.setText("Submit Query");

        jLabel15.setText("Format");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "Test", "ODI", "T20" }));

        jLabel17.setText("to");

        jLabel19.setText("to");

        jLabel23.setText("to");

        jLabel25.setText("to");

        jLabel27.setText("to");

        bowlingMatchesPlayed.setText("Matches Played");
        bowlingMatchesPlayed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bowlingMatchesPlayedActionPerformed(evt);
            }
        });

        bowlingWicketsTaken.setText("Wickets Taken");
        bowlingWicketsTaken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bowlingWicketsTakenActionPerformed(evt);
            }
        });

        bowlingEconomyRate.setText("Economy Rate");
        bowlingEconomyRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bowlingEconomyRateActionPerformed(evt);
            }
        });

        bowling5Wickets.setText("5 Wicket Hauls");
        bowling5Wickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bowling5WicketsActionPerformed(evt);
            }
        });

        bowlingAverage.setText("Average");
        bowlingAverage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bowlingAverageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBallingLayout = new javax.swing.GroupLayout(panelBalling);
        panelBalling.setLayout(panelBallingLayout);
        panelBallingLayout.setHorizontalGroup(
            panelBallingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBallingLayout.createSequentialGroup()
                .addGroup(panelBallingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBallingLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jButton2))
                    .addGroup(panelBallingLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(panelBallingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(panelBallingLayout.createSequentialGroup()
                                .addGroup(panelBallingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bowlingMatchesPlayed)
                                    .addComponent(jLabel3)
                                    .addGroup(panelBallingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(bowlingWicketsTaken)
                                        .addGroup(panelBallingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bowling5Wickets)
                                            .addComponent(bowlingEconomyRate)
                                            .addComponent(bowlingAverage))))
                                .addGap(34, 34, 34)
                                .addGroup(panelBallingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboBoxTeamBowling, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelBallingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(panelBallingLayout.createSequentialGroup()
                                            .addComponent(bowlingEconomyMin, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel23)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(bowlingEconomyMax, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(panelBallingLayout.createSequentialGroup()
                                            .addGroup(panelBallingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(panelBallingLayout.createSequentialGroup()
                                                    .addComponent(bowlingMatchesMin, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBallingLayout.createSequentialGroup()
                                                    .addComponent(bowlingWicketsMin, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                            .addGroup(panelBallingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(panelBallingLayout.createSequentialGroup()
                                                    .addComponent(jLabel19)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(bowlingWicketsMax, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(panelBallingLayout.createSequentialGroup()
                                                    .addComponent(jLabel17)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(bowlingMatchesMax, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelBallingLayout.createSequentialGroup()
                                            .addGroup(panelBallingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(bowling5WicketMin, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(bowlingAverageMin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(panelBallingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(panelBallingLayout.createSequentialGroup()
                                                    .addComponent(jLabel27)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(bowlingAverageMax, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(panelBallingLayout.createSequentialGroup()
                                                    .addComponent(jLabel25)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(bowling5WicketMax, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))))))))
                .addGap(18, 18, 18)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBallingLayout.setVerticalGroup(
            panelBallingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBallingLayout.createSequentialGroup()
                .addGroup(panelBallingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBallingLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBallingLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(panelBallingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(comboBoxTeamBowling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelBallingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelBallingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bowlingMatchesMin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bowlingMatchesMax, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(bowlingMatchesPlayed))
                        .addGap(18, 18, 18)
                        .addGroup(panelBallingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bowlingWicketsMin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(bowlingWicketsMax, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bowlingWicketsTaken))
                        .addGap(18, 18, 18)
                        .addGroup(panelBallingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bowlingEconomyMin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bowlingEconomyMax, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(bowlingEconomyRate))
                        .addGap(22, 22, 22)
                        .addGroup(panelBallingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bowling5WicketMin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bowling5WicketMax, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)
                            .addComponent(bowling5Wickets))
                        .addGap(18, 18, 18)
                        .addGroup(panelBallingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bowlingAverageMin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27)
                            .addComponent(bowlingAverageMax, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bowlingAverage))
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        JTabbedPanel.addTab("      Bowling       ", panelBalling);

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/rhodes.jpg"))); // NOI18N

        jLabel28.setText("Team");

        jLabel30.setText("Format");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "Test", "ODI", "T20" }));

        jLabel31.setText("Matches Played");

        jLabel32.setText("to");

        jLabel33.setText("Catches");

        jLabel34.setText("to");

        jLabel35.setText("Stumpings");

        jLabel36.setText("to");

        jButton3.setText("Submit Query");

        javax.swing.GroupLayout panelFieldingLayout = new javax.swing.GroupLayout(panelFielding);
        panelFielding.setLayout(panelFieldingLayout);
        panelFieldingLayout.setHorizontalGroup(
            panelFieldingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFieldingLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panelFieldingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31)
                    .addComponent(jLabel33)
                    .addComponent(jLabel35))
                .addGap(20, 20, 20)
                .addGroup(panelFieldingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFieldingLayout.createSequentialGroup()
                        .addComponent(jSpinner25, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpinner26, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFieldingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(comboBoxTeamFielding, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFieldingLayout.createSequentialGroup()
                        .addGroup(panelFieldingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinner21, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner23, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelFieldingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34)
                            .addComponent(jLabel32))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelFieldingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinner22, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner24, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton3))
                .addGap(66, 66, 66)
                .addComponent(jLabel29)
                .addContainerGap(127, Short.MAX_VALUE))
        );
        panelFieldingLayout.setVerticalGroup(
            panelFieldingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFieldingLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelFieldingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFieldingLayout.createSequentialGroup()
                        .addGroup(panelFieldingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(comboBoxTeamFielding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelFieldingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelFieldingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(jSpinner21, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32)
                            .addComponent(jSpinner22, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(panelFieldingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(jLabel34)
                            .addComponent(jSpinner23, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner24, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelFieldingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(jLabel36)
                            .addComponent(jSpinner25, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner26, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addComponent(jButton3))
                    .addComponent(jLabel29))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        JTabbedPanel.addTab("        Fielding        ", panelFielding);

        jLabel37.setText("Format");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "Test", "ODI", "T20" }));

        jLabel38.setText("Matches Officiated");

        jLabel40.setText("to");

        jButton4.setText("Submit Query");

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/bowden.jpg"))); // NOI18N

        javax.swing.GroupLayout panelUmpireLayout = new javax.swing.GroupLayout(panelUmpire);
        panelUmpire.setLayout(panelUmpireLayout);
        panelUmpireLayout.setHorizontalGroup(
            panelUmpireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUmpireLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(panelUmpireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38)
                    .addComponent(jLabel37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelUmpireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addGroup(panelUmpireLayout.createSequentialGroup()
                        .addComponent(jSpinner27, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpinner28, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel39)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        panelUmpireLayout.setVerticalGroup(
            panelUmpireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUmpireLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(panelUmpireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panelUmpireLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(jSpinner27, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40)
                    .addComponent(jSpinner28, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUmpireLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel39)
                .addContainerGap())
        );

        JTabbedPanel.addTab("         Umpire       ", panelUmpire);

        jLabel41.setText("Team");

        jLabel42.setText("Format");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "Test", "ODI", "T20" }));

        jLabel43.setText("Matches Played");

        jLabel44.setText("to");

        jLabel45.setText("Matches Won");

        jLabel46.setText("to");

        jLabel47.setText("Matches Lost");

        jLabel48.setText("to");

        jButton5.setText("Submit Query");

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/india.jpg"))); // NOI18N

        jLabel50.setText("Matches Drawn");

        jLabel51.setText("to");

        jLabel52.setText("Matches Tied");

        jLabel53.setText("to");

        javax.swing.GroupLayout panelCountryLayout = new javax.swing.GroupLayout(panelCountry);
        panelCountry.setLayout(panelCountryLayout);
        panelCountryLayout.setHorizontalGroup(
            panelCountryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCountryLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panelCountryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel41)
                    .addComponent(jLabel42)
                    .addComponent(jLabel43)
                    .addComponent(jLabel45)
                    .addComponent(jLabel47)
                    .addComponent(jLabel50)
                    .addComponent(jLabel52))
                .addGap(20, 20, 20)
                .addGroup(panelCountryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelCountryLayout.createSequentialGroup()
                        .addComponent(jSpinner35, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel51)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpinner36, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCountryLayout.createSequentialGroup()
                        .addComponent(jSpinner33, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel48)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpinner34, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(comboBoxTeamCountry, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelCountryLayout.createSequentialGroup()
                        .addGroup(panelCountryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinner29, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner31, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCountryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel46)
                            .addComponent(jLabel44))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelCountryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinner30, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner32, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton5)
                    .addGroup(panelCountryLayout.createSequentialGroup()
                        .addComponent(jSpinner37, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel53)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSpinner38, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        panelCountryLayout.setVerticalGroup(
            panelCountryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCountryLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelCountryLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelCountryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(comboBoxTeamCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCountryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCountryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(jSpinner29, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44)
                    .addComponent(jSpinner30, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(panelCountryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(jLabel46)
                    .addComponent(jSpinner31, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner32, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCountryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(jLabel48)
                    .addComponent(jSpinner33, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner34, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelCountryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner35, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel51)
                    .addComponent(jSpinner36, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel50))
                .addGap(18, 18, 18)
                .addGroup(panelCountryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner37, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner38, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel53)
                    .addComponent(jLabel52))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(63, 63, 63))
        );

        JTabbedPanel.addTab("      Country       ", panelCountry);

        jLabel54.setText("Team 1");

        jLabel55.setText("Team 2");

        jLabel56.setText("Winner");

        jLabel57.setText("Format");

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "Test", "ODI", "T20" }));

        jLabel60.setText("Location");

        jLabel61.setText("Umpired by");

        jButton6.setText("Submit Query");

        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/match.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel54)
                            .addGap(84, 84, 84)
                            .addComponent(comboBoxTeamCountry1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel55)
                                .addComponent(jLabel57)
                                .addComponent(jLabel56))
                            .addGap(84, 84, 84)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(comboBoxTeamCountry3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboBoxTeamCountry2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox6, 0, 200, Short.MAX_VALUE))))
                        .addComponent(jLabel60)
                        .addComponent(jLabel61))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(comboBoxTeamCountry5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(137, 137, 137)
                            .addComponent(comboBoxTeamCountry4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel54)
                            .addComponent(comboBoxTeamCountry1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel55)
                            .addComponent(comboBoxTeamCountry2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel57)
                            .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel56)
                            .addComponent(comboBoxTeamCountry3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel60)
                            .addComponent(comboBoxTeamCountry4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel62))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel61)
                    .addComponent(comboBoxTeamCountry5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jButton6)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        JTabbedPanel.addTab("Match", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(JTabbedPanel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTabbedPanel))
        );

        JTabbedPanel.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void battingMatchesPlayedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_battingMatchesPlayedActionPerformed
        // TODO add your handling code here:
        battingMatchesMin.setEnabled(battingMatchesPlayed.isSelected());
        battingMatchesMax.setEnabled(battingMatchesPlayed.isSelected());
    }//GEN-LAST:event_battingMatchesPlayedActionPerformed

    private void battingRunsScoredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_battingRunsScoredActionPerformed
        // TODO add your handling code here:
        battingRunsMin.setEnabled(battingRunsScored.isSelected());
        battingRunsMax.setEnabled(battingRunsScored.isSelected());
    }//GEN-LAST:event_battingRunsScoredActionPerformed

    private void battingHighestScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_battingHighestScoreActionPerformed
        // TODO add your handling code here:
        battingHighestMin.setEnabled(battingHighestScore.isSelected());
        battingHighestMax.setEnabled(battingHighestScore.isSelected());
    }//GEN-LAST:event_battingHighestScoreActionPerformed

    private void battingHundredsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_battingHundredsActionPerformed
        // TODO add your handling code here:
        battingHundredsMin.setEnabled(battingHundreds.isSelected());
        battingHundredsMax.setEnabled(battingHundreds.isSelected());
    }//GEN-LAST:event_battingHundredsActionPerformed

    private void battingFiftiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_battingFiftiesActionPerformed
        // TODO add your handling code here:
        battingFiftiesMin.setEnabled(battingFifties.isSelected());
        battingFiftiesMax.setEnabled(battingFifties.isSelected());
    }//GEN-LAST:event_battingFiftiesActionPerformed

    private void battingStrikeRatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_battingStrikeRatesActionPerformed
        // TODO add your handling code here:
        battingStrikeRateMin.setEnabled(battingStrikeRates.isSelected());
        battingStrikeRateMax.setEnabled(battingStrikeRates.isSelected());
    }//GEN-LAST:event_battingStrikeRatesActionPerformed
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        BattingQueryObj obj = new BattingQueryObj();
        if(battingMatchesPlayed.isSelected())
        {
            obj.mplayed_low = (Integer) battingMatchesMin.getValue();
            obj.mplayed_high = (Integer) battingMatchesMax.getValue();
        }
        if(battingRunsScored.isSelected())
        {
            obj.runs_low = (Integer) battingRunsMin.getValue();
            obj.runs_high = (Integer) battingRunsMax.getValue();
        }
        if(battingHundreds.isSelected())
        {
            obj.hundreds_low = (Integer) battingHundredsMin.getValue();
            obj.hundreds_high = (Integer) battingHundredsMax.getValue();
        }
        if(battingFifties.isSelected())
        {
            obj.fifties_low = (Integer) battingFiftiesMin.getValue();
            obj.fifties_high = (Integer) battingFiftiesMax.getValue();
        }
        if(battingStrikeRates.isSelected())
        {
            obj.strike_low = (Integer) battingStrikeRateMin.getValue();
            obj.mplayed_high = (Integer) battingStrikeRateMax.getValue();
        }
        
        ResultWindow rw = new ResultWindow();
        rw.result = Queries.getBatsmen(obj);
        rw.columnNames = new String[] {"Name",       "Country",      "Runs", "Matches", "Innings", "Not Outs"};
        rw.queryNames = new String[] {"Player.Name", "Country.Name", "Runs", "Mat",     "Inns",    "NO" };
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bowlingMatchesPlayedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bowlingMatchesPlayedActionPerformed
        // TODO add your handling code here:
        bowlingMatchesMin.setEnabled(bowlingMatchesPlayed.isSelected());
        bowlingMatchesMax.setEnabled(bowlingMatchesPlayed.isSelected());
    }//GEN-LAST:event_bowlingMatchesPlayedActionPerformed

    private void bowlingWicketsTakenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bowlingWicketsTakenActionPerformed
        // TODO add your handling code here:
        bowlingWicketsMin.setEnabled(bowlingWicketsTaken.isSelected());
        bowlingWicketsMax.setEnabled(bowlingWicketsTaken.isSelected());
    }//GEN-LAST:event_bowlingWicketsTakenActionPerformed

    private void bowlingEconomyRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bowlingEconomyRateActionPerformed
        // TODO add your handling code here:
        bowlingEconomyMin.setEnabled(bowlingEconomyRate.isSelected());
        bowlingEconomyMax.setEnabled(bowlingEconomyRate.isSelected());
    }//GEN-LAST:event_bowlingEconomyRateActionPerformed

    private void bowling5WicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bowling5WicketsActionPerformed
        // TODO add your handling code here:
        bowling5WicketMin.setEnabled(bowling5Wickets.isSelected());
        bowling5WicketMax.setEnabled(bowling5Wickets.isSelected());
    }//GEN-LAST:event_bowling5WicketsActionPerformed

    private void bowlingAverageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bowlingAverageActionPerformed
        // TODO add your handling code here:
        bowlingAverageMin.setEnabled(bowlingAverage.isSelected());
        bowlingAverageMax.setEnabled(bowlingAverage.isSelected());
    }//GEN-LAST:event_bowlingAverageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane JTabbedPanel;
    private javax.swing.JRadioButton battingFifties;
    private javax.swing.JSpinner battingFiftiesMax;
    private javax.swing.JSpinner battingFiftiesMin;
    private javax.swing.JSpinner battingHighestMax;
    private javax.swing.JSpinner battingHighestMin;
    private javax.swing.JRadioButton battingHighestScore;
    private javax.swing.JRadioButton battingHundreds;
    private javax.swing.JSpinner battingHundredsMax;
    private javax.swing.JSpinner battingHundredsMin;
    private javax.swing.JSpinner battingMatchesMax;
    private javax.swing.JSpinner battingMatchesMin;
    private javax.swing.JRadioButton battingMatchesPlayed;
    private javax.swing.JSpinner battingRunsMax;
    private javax.swing.JSpinner battingRunsMin;
    private javax.swing.JRadioButton battingRunsScored;
    private javax.swing.JSpinner battingStrikeRateMax;
    private javax.swing.JSpinner battingStrikeRateMin;
    private javax.swing.JRadioButton battingStrikeRates;
    private javax.swing.JSpinner bowling5WicketMax;
    private javax.swing.JSpinner bowling5WicketMin;
    private javax.swing.JRadioButton bowling5Wickets;
    private javax.swing.JRadioButton bowlingAverage;
    private javax.swing.JSpinner bowlingAverageMax;
    private javax.swing.JSpinner bowlingAverageMin;
    private javax.swing.JSpinner bowlingEconomyMax;
    private javax.swing.JSpinner bowlingEconomyMin;
    private javax.swing.JRadioButton bowlingEconomyRate;
    private javax.swing.JSpinner bowlingMatchesMax;
    private javax.swing.JSpinner bowlingMatchesMin;
    private javax.swing.JRadioButton bowlingMatchesPlayed;
    private javax.swing.JSpinner bowlingWicketsMax;
    private javax.swing.JSpinner bowlingWicketsMin;
    private javax.swing.JRadioButton bowlingWicketsTaken;
    private javax.swing.JComboBox comboBoxTeamBatting;
    private javax.swing.JComboBox comboBoxTeamBowling;
    private javax.swing.JComboBox comboBoxTeamCountry;
    private javax.swing.JComboBox comboBoxTeamCountry1;
    private javax.swing.JComboBox comboBoxTeamCountry2;
    private javax.swing.JComboBox comboBoxTeamCountry3;
    private javax.swing.JComboBox comboBoxTeamCountry4;
    private javax.swing.JComboBox comboBoxTeamCountry5;
    private javax.swing.JComboBox comboBoxTeamFielding;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner21;
    private javax.swing.JSpinner jSpinner22;
    private javax.swing.JSpinner jSpinner23;
    private javax.swing.JSpinner jSpinner24;
    private javax.swing.JSpinner jSpinner25;
    private javax.swing.JSpinner jSpinner26;
    private javax.swing.JSpinner jSpinner27;
    private javax.swing.JSpinner jSpinner28;
    private javax.swing.JSpinner jSpinner29;
    private javax.swing.JSpinner jSpinner30;
    private javax.swing.JSpinner jSpinner31;
    private javax.swing.JSpinner jSpinner32;
    private javax.swing.JSpinner jSpinner33;
    private javax.swing.JSpinner jSpinner34;
    private javax.swing.JSpinner jSpinner35;
    private javax.swing.JSpinner jSpinner36;
    private javax.swing.JSpinner jSpinner37;
    private javax.swing.JSpinner jSpinner38;
    private javax.swing.JPanel panelBalling;
    private javax.swing.JPanel panelBatting;
    private javax.swing.JPanel panelCountry;
    private javax.swing.JPanel panelFielding;
    private javax.swing.JPanel panelUmpire;
    // End of variables declaration//GEN-END:variables
}
